config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users
  resources :users


  # resources :users do
  #michael .....
  #   resources :products
  # end
  resources :charges
  
  root 'products#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # if routes doesn't match
  get '*path' => redirect('/')


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  

  
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user, :foreign_key => :sellerId, :primary_key => :id
    mount_uploaders :images, ImageUploader
    validates :sellerId,:images,:name,:price,:location, presence: true    
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, :foreign_key => :sellerId, :primary_key => :id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

   validates :first_name,:last_name, presence: true    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#to add custom field data from devise to to database.
before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
  # saving from fake users
  #protect_from_forgery with: :exception

  helper_method :admin?
  
  def admin?
    current_user.email == "punyachapagain@gmail.com"
  end

  

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    
   
    @amount = params[:price]
    @name = params[:name]

  end
  
  def create
    # Amount in cents
    @amount = 5000
  
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
  
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
      
    )

    
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.all
    # if user_signed_in?
    #   @p = @products.where(sellerId: current_user.id)
    # end
    #byebug
    if params[:val] == nil
      @products = Product.all
    elsif params[:val] == "New"
      @products = Product.where(condition: params[:val])
    elsif params[:val] == "Old"
      @products = Product.where(condition: params[:val])
    elsif params[:val] == "Unused"
      @products = Product.where(condition: params[:val])
    #byebug
    # @products = if params[:user_id] and (params[:user_id] = current_user.try(:id))
    #   Product.where(sellerId: params[:user_id])
    elsif params[:val] == "User"
      
      @products = Product.where(sellerId: current_user.id)

    else
      redirect_to root_path
    end

    
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
   
    @product = Product.new
    
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    
    @product = Product.new(product_params)
    @product.sellerId = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  # def newlisting 
  #   @products = Product.where(condition: :New)
  #   #@products = Product.find(params[:product])
  # end

  # def unusedlisting 
  #   @products = Product.where(condition: :Unused)
  #   #@products = Product.find(params[:product])
  # end

  # def oldlisting 
  #   @products = Product.where(condition: :Old)
  #   #@products = Product.find(params[:product])
  # end

  # def userlisting 
    
  #   @products = Product.all
    
    
  # end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :condition, :location, :category, :sellerId, {images: []})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    if user_signed_in?
      redirect_to root_path
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2 class = "thank-you"> Thanks, you for shopping with us you   </h2>

<%= link_to "Go back to Home page", root_path%>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
    <table class = "charge-table">
    <tr>
      <th>
        <span>Name:    <%= @name %></span>
      </th>
    </tr>
    <td>
      <span>Amount:   $<%= @amount %></span>
    </td>
    </table>
      
      
      
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount = <%= @amount.to_i * 100%>
          data-locale="auto"></script>
<% end %>

app/views/layouts/_footer.html.erb
<div id = "footer">
    <h3> Contact Us</h3>
</div>

app/views/layouts/_header.html.erb
<div id = "header">

    <h2>Toys World <h2>

    
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: 'navbar-brand',id: 'navdecoration'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "New",root_path(@products, val: :New) %></li>
        <li><%= link_to "Old",root_path(@products,val: :Old) %></li>
        <li><%= link_to "Unused",root_path(@products,val: :Unused) %></li> 
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Post Ad", new_product_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "View Listing", root_path(@products, val: :User )%></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            
          </ul>
        </li>

        <%else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Post Ad", new_user_session_path %></li>

        <% end %>
        
        
      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToysStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Skranji" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/navbar' %>
    
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows:5, cols:22 %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <% @condi =["New","Old","Unused"]%>
  <div class="field">
    <%= form.label :condition %>
    <% @condi = ["New","Old","Unused"] %>
    <%= form.select :condition, options_for_select(@condi)%>
  </div>


  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location%>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%#= form.label :sellerId %>
    <%#= form.number_field :sellerId %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container-fluid new-products" >

    <h1>Editing Product</h1>

    <%= render 'form', product: @product %>

    <%= link_to 'Show', @product %> |
    <%= link_to 'Back', products_path %>

</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h3>Products</h3>
  <div class="table-responsive">          
  
    
    
    <% @products.each do |product| %>
    <table class="table">
      <thead> 
        
        <tr>
          <td><%= image_tag(product.images[0].url,style: 'height:100px;width:150px;' )%></td>
        </tr>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.condition %></td>
        </tr>
        <tr>
          <td><%= product.price %></td>
          
        </tr>
        <tr>
          <td>
            <% if user_signed_in? and (product.sellerId == current_user.id)%>
              <button type="button" class="btn btn-warning">
              <%= link_to 'Edit', edit_product_path(product) %> </button></td>
            <% elsif user_signed_in?%>
              <button type="button" class="btn btn-success" >
                <%= link_to "Buy Now", new_charge_path(product,price: product.price, name: product.name) %>
              </button>
            <% else %>
              <button type="button"  class="btn btn-success">
                <%= link_to "Buy Now", new_user_session_path %>
              </button></td>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><button type="button" class="btn btn-info"><%= link_to 'Show', product%>  </button></td>
        </tr>
      </thead>
    </table>
    <% end %>
    

    
  
  </div>
</div>

app/views/products/new.html.erb
<div class="container-fluid new-products" >
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

</div>

app/views/products/newlisting.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2>Products</h2>
  <div class="table-responsive">          
  
    
    
    <% @products.each do |product| %>
    <table class="table">
      <thead> 
        
        <tr>
          <td><%= image_tag(product.images[0].url,style: 'height:100px;width:150px;' )%></td>
        </tr>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.condition %></td>
        </tr>
        <tr>
          <td><%= product.price %></td>
          
        </tr>
        <tr>
          <td>
            <% if user_signed_in? and (product.sellerId == current_user.id)%>
              <button type="button" class="btn btn-warning">
              <%= link_to 'Edit', edit_product_path(product) %> </button></td>
            <% elsif user_signed_in?%>
              <button type="button" class="btn btn-success">
                  <%= link_to "Buy Now", new_charge_path(product,price: product.price) %>
              </button>
            <% else %>
              <button type="button" class="btn btn-success">
                <%= link_to "Buy Now", new_user_session_path %>
              </button></td>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><button type="button" class="btn btn-info"><%= link_to 'Show', product%>  </button></td>
        </tr>
      </thead>
    </table>
    <% end %>
    

    
  
  </div>
</div>

app/views/products/oldlisting.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2>Products</h2>
  <div class="table-responsive">          
  
    
    
    <% @products.each do |product| %>
    <table class="table">
      <thead> 
        
        <tr>
          <td><%= image_tag(product.images[0].url,style: 'height:100px;width:150px;' )%></td>
        </tr>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.condition %></td>
        </tr>
        <tr>
          <td><%= product.price %></td>
          
        </tr>
        <tr>
          <td>
            <% if user_signed_in? and (product.sellerId == current_user.id)%>
              <button type="button" class="btn btn-warning">
              <%= link_to 'Edit', edit_product_path(product) %> </button></td>
            <% elsif user_signed_in?%>
              <button type="button" class="btn btn-success">
                  <%= link_to "Buy Now", new_charge_path(product,price: product.price) %>
              </button>
            <% else %>
              <button type="button" class="btn btn-success">
                <%= link_to "Buy Now", new_user_session_path %>
              </button></td>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><button type="button" class="btn btn-info"><%= link_to 'Show', product%>  </button></td>
        </tr>
      </thead>
    </table>
    <% end %>
    

    
  
  </div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

      
<div class="container-fluid new-products" >    
<div class="row">
	
              
            
    <div class="col-sm-4">
    	<div class="row-sm-9">
      				
        <%= link_to image_tag(@product.images[0].url,class: "style-image1"), @product.images[0].url %>
    	</div>
        <div class="row-sm" >
              <% @product.images.each do | image|%>
                  <%=link_to image_tag(image.url,class: "style-image"),image.url,target: "_blank", alt: "image"%>
                  
                  
                  
              <% end %>
              <%= @a%>
    </div>
    	
    </div>
  
     <div class="col-sm-4">
            
            <div class="row-xs  product-display" >
                Name: <%= @product.name %>
            </div>
            <div class="row-xs  product-display" >
              Description:  <%= @product.description%>
            </div>
            <div class="row-xs  product-display" >
              Located at: <%= @product.location %> 
            </div>
            <div class="row-xs  product-display" >
              Conditon: <%= @product.condition %>
            </div>
            <div class="row-xs  product-display" >
              Price: <%= @product.price %> 
            </div>
            <div class="row-xs  product-display" >
              Category: <%= @product.category %>
            </div>
            <div class="row-xs  product-display" >
            <% if user_signed_in? and (@product.sellerId == current_user.id)%>
              <button type="button" class="btn btn-warning">
              <%= link_to 'Edit', edit_product_path(@product) %> </button>
            <% elsif user_signed_in?%>
              <button type="button" class="btn btn-success">
                  <%= link_to "Buy Now", new_charge_path(@product,price: @product.price) %>
              </button>
            <% else %>
              <button type="button" class="btn btn-success">
                <%= link_to "Buy Now", new_user_session_path %>
              </button></td>
            <% end %>
            </div>

      
  		</div>
      
    </div>
  <button type="button" class="btn btn-primary"><%= link_to 'Back', products_path %></button></td>
  </div>
  </div>

  

app/views/products/unusedlisting.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2>Products</h2>
  <div class="table-responsive">          
  
    
    
    <% @products.each do |product| %>
    <table class="table">
      <thead> 
        
        <tr>
          <td><%= image_tag(product.images[0].url,style: 'height:100px;width:150px;' )%></td>
        </tr>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.condition %></td>
        </tr>
        <tr>
          <td><%= product.price %></td>
          
        </tr>
        <tr>
          <td>
            <% if user_signed_in? and (product.sellerId == current_user.id)%>
              <button type="button" class="btn btn-warning">
              <%= link_to 'Edit', edit_product_path(product) %> </button></td>
            <% elsif user_signed_in?%>
              <button type="button" class="btn btn-success">
                  <%= link_to "Buy Now", new_charge_path(product,price: product.price) %>
              </button>
            <% else %>
              <button type="button" class="btn btn-success">
                <%= link_to "Buy Now", new_user_session_path %>
              </button></td>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><button type="button" class="btn btn-info"><%= link_to 'Show', product%>  </button></td>
        </tr>
      </thead>
    </table>
    <% end %>
    

    
  
  </div>
</div>

app/views/products/userlisting.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2>Products</h2>
  <div class="table-responsive">          
  
    
    
    <% @products.each do |product| %>
    <% if user_signed_in? and (product.sellerId == current_user.id)%>
    <table class="table">
      <thead> 
        
        <tr>
          <td><%= image_tag(product.images[0].url,style: 'height:100px;width:150px;' )%></td>
        </tr>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.condition %></td>
        </tr>
        <tr>
          <td><%= product.price %></td>
          
        </tr>
        <tr>
          <td>
            
              <button type="button" class="btn btn-warning">
              <%= link_to 'Edit', edit_product_path(product) %> </button>
        </td>
        </tr>
        <tr>
        <td>
              <button type="button" class="btn btn-danger">
                <%= link_to "Delete", product, method: :delete, data: { confirm: 'Are you sure?' } %>
              </button>
        </td>
        </tr>
            
          
        </tr>
        
      </thead>
    </table>
    <% end %>
    <% end %>
    

    
  
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if false %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<%#= link_to "Sign Out", destroy_user_session_path, method: :delete %>

app/views/users/index.html.erb
<% if admin?%>
<p id="notice"><%= notice %></p>

<h1>Admin</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>

  </tbody>
  
</table>

<br>
<% else %>
  <h1> You are not an Admin Go to home page </h1>
<%end%>

<%#= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>
<%#= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>